url: 'https://ktdolls2017.net'
title: KTDolls
subtitle: Pedigreed Traditional and Mink Ragdoll Kittens
email: ktdolls2017@gmail.com
phone: 281-766-0633
description: >-
  KTDolls is a family-owned cattery breeding pedigreed Ragdoll kittens.
  Established in 2017, we are located in Katy, Texas, 30 miles west of downtown
  Houston.
permalink: none
markdown: kramdown
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
include:
  - _pages
  - _redirects
social:
  - title: Facebook
    url: 'https://www.facebook.com/KTDolls/'
  - title: Instagram
    url: 'https://www.instagram.com/ktdolls2017/'
logo: /assets/img/logo.jpg
imagemagick:
  enabled: true
  widths:
    - 1024
  input_directories:
    - uploads
  input_formats:
    - .jpg
    - .jpeg
  output_formats:
    jpg: >-
      -auto-orient -strip -resize x650 -quality 85 -define jpeg:dct-method=float
      -interlace Plane
    webp: '-auto-orient -resize x650 -quality 85'
_template: settings
exclude:
  - screenshots/
  - Forestry.io Guide.docx
  - README.md
