url: https://christopherstraub.github.io/ktdolls/

# Site settings
title: KTDolls
email: ktdolls2017@gmail.com
description: 'KTDolls is a family-owned cattery breeding pedigreed Ragdoll kittens. Established in 2017, we are located in Katy, Texas, 30 miles west of downtown Houston.'
baseurl: /ktdolls

# Build settings
markdown: kramdown

# Team names, titles and social links
people:
  - name: Princess Patience
    pic: 1
    position: Princess Patience is a beautiful Blue Colorpoint Mink.
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

  - name: Lady Annabella
    pic: 2
    position: Lady Annabella is a beautiful Blue Colorpoint Bicolor.
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Sir Glenn
    pic: 3
    position: Sir Glenn is a handsome Seal Colorpoint Traditional.
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/KTDolls/
  - title: instagram
    url: https://www.instagram.com/ktdolls2017/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210
