url: https://y7kim.github.io
baseurl: /ktdolls

# Site settings
title: KTDolls
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.'

# Team names, titles and social links
people:
  - name: Princess Patience
    pic: 1
    position: Princess Patience is a beautiful Blue Colorpoint Mink.
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

  - name: Lady Annabella
    pic: 2
    position: Lady Annabella is a beautiful Blue Colorpoint Bicolor.
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Sir Glenn
    pic: 3
    position: Sir Glenn is a handsome Seal Colorpoint Traditional.
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/KTDolls/
  - title: instagram
    url: https://www.instagram.com/ktdolls2017/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
