---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: _config.yml
  label: Site Settings
- type: heading
  label: Website
- type: document
  path: index.html
  label: Home Page
- type: document
  path: _pages/about.html
  label: About Page
- type: document
  path: _pages/past-litters.html
  label: Past Litters Page
- type: document
  path: _pages/fur-ever-homes.html
  label: Fur-ever Homes Page
- type: document
  path: _data/theme.yml
  label: Theme
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
