---
label: Settings
hide_body: true
fields:
- name: email
  type: text
  config:
    required: false
  label: Email
  description: Contact email.
- name: phone
  type: text
  config:
    required: false
  label: Contact Number
  description: Contact phone/text number.
- name: logo
  type: file
  config:
    maxSize: 64
  label: Logo
  description: The logo appears in the footer.
- name: title
  type: text
  config:
    required: false
  label: Site Title
  description: The title of the website.
- name: subtitle
  type: text
  config:
    required: false
  label: Site Subtitle
  description: The subtitle of the website.
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Site Description
  description: A description of the website.
- name: social
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Title
    description: The title of the social media platform.
  - name: url
    type: text
    config:
      required: false
    label: Link
    description: The link to your profile/page on the social media platform.
  config:
    min: 
    max: 
    labelField: 
  label: Social Media Links
  description: List of social media links.
- name: url
  type: text
  config:
    required: false
  label: Site URL
  description: The site URL. Must not have a trailing slash.
pages:
- _config.yml
